/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as SiteVerifyAccessRouteImport } from './routes/_site.verify-access'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SitePortfolioRouteImport } from './routes/_site.portfolio'
import { Route as SiteListPropertyRouteImport } from './routes/_site.list-property'
import { Route as SiteInvestorsRouteImport } from './routes/_site.investors'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteBlogRouteImport } from './routes/_site.blog'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SitePropertiesIndexRouteImport } from './routes/_site.properties.index'
import { Route as SitePropertiesSlugRouteImport } from './routes/_site.properties.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const SiteVerifyAccessRoute = SiteVerifyAccessRouteImport.update({
  id: '/verify-access',
  path: '/verify-access',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SitePortfolioRoute = SitePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => SiteRoute,
} as any)
const SiteListPropertyRoute = SiteListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInvestorsRoute = SiteInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SitePropertiesIndexRoute = SitePropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePropertiesSlugRoute = SitePropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/investors': typeof SiteInvestorsRoute
  '/list-property': typeof SiteListPropertyRoute
  '/portfolio': typeof SitePortfolioRoute
  '/services': typeof SiteServicesRoute
  '/verify-access': typeof SiteVerifyAccessRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/properties/$slug': typeof SitePropertiesSlugRoute
  '/properties/': typeof SitePropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/investors': typeof SiteInvestorsRoute
  '/list-property': typeof SiteListPropertyRoute
  '/portfolio': typeof SitePortfolioRoute
  '/services': typeof SiteServicesRoute
  '/verify-access': typeof SiteVerifyAccessRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthIndexRoute
  '/properties/$slug': typeof SitePropertiesSlugRoute
  '/properties': typeof SitePropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/blog': typeof SiteBlogRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/investors': typeof SiteInvestorsRoute
  '/_site/list-property': typeof SiteListPropertyRoute
  '/_site/portfolio': typeof SitePortfolioRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/verify-access': typeof SiteVerifyAccessRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_site/': typeof SiteIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_site/properties/$slug': typeof SitePropertiesSlugRoute
  '/_site/properties/': typeof SitePropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/blog'
    | '/contact'
    | '/investors'
    | '/list-property'
    | '/portfolio'
    | '/services'
    | '/verify-access'
    | '/auth/verify'
    | '/auth/'
    | '/properties/$slug'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/blog'
    | '/contact'
    | '/investors'
    | '/list-property'
    | '/portfolio'
    | '/services'
    | '/verify-access'
    | '/auth/verify'
    | '/'
    | '/auth'
    | '/properties/$slug'
    | '/properties'
  id:
    | '__root__'
    | '/_site'
    | '/auth'
    | '/_site/about'
    | '/_site/blog'
    | '/_site/contact'
    | '/_site/investors'
    | '/_site/list-property'
    | '/_site/portfolio'
    | '/_site/services'
    | '/_site/verify-access'
    | '/auth/verify'
    | '/_site/'
    | '/auth/'
    | '/_site/properties/$slug'
    | '/_site/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_site/verify-access': {
      id: '/_site/verify-access'
      path: '/verify-access'
      fullPath: '/verify-access'
      preLoaderRoute: typeof SiteVerifyAccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/portfolio': {
      id: '/_site/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof SitePortfolioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/list-property': {
      id: '/_site/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof SiteListPropertyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/investors': {
      id: '/_site/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof SiteInvestorsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/properties/': {
      id: '/_site/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof SitePropertiesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/properties/$slug': {
      id: '/_site/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof SitePropertiesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBlogRoute: typeof SiteBlogRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteInvestorsRoute: typeof SiteInvestorsRoute
  SiteListPropertyRoute: typeof SiteListPropertyRoute
  SitePortfolioRoute: typeof SitePortfolioRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteVerifyAccessRoute: typeof SiteVerifyAccessRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePropertiesSlugRoute: typeof SitePropertiesSlugRoute
  SitePropertiesIndexRoute: typeof SitePropertiesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBlogRoute: SiteBlogRoute,
  SiteContactRoute: SiteContactRoute,
  SiteInvestorsRoute: SiteInvestorsRoute,
  SiteListPropertyRoute: SiteListPropertyRoute,
  SitePortfolioRoute: SitePortfolioRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteVerifyAccessRoute: SiteVerifyAccessRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePropertiesSlugRoute: SitePropertiesSlugRoute,
  SitePropertiesIndexRoute: SitePropertiesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AuthRouteChildren {
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
